### ISSUE TITLE
[Question] Newline characters in replacement map

### ISSUE THREAD

**Issue by ajthemacboy** [jfgiraud/sandr#1]
Hi, sorry to open an issue to ask this, but I was wondering how I can use newline characters in the replacement list when using the -a argument.

Here's a snippet of my replacement map;

`:17.0 => :17.12`
`:17.1 => :17.12`
`:17.2 => :17.12`
`:17.3 => :17.12`
`:17.4 => :17.12`
`:17.5 => :17.12`
`:17.6 => :17.12`
`:17.7 => :17.12`
`:17.8 => :17.12`
`:17.9 => :17.12`
`:17.10 => :17.12`
`:17.11 => :17.12`
`:17.13 => :17.12`

However, you as you  might expect, this causes errors; `:17.1` gets replaced to `:17.12`, so the final output becomes `:17.122`. Because each string I want to replace is at the end of a line, the obvious solution is to use a newline character in the replacement map, but that doesn't seem to work; I've tried both \r and \n and neither produce the desired output.

Is there something I can do, or is this a limitation of the script, or perhaps my own error?

**Comment by jfgiraud** [comment]
Hello,

Could you confirm that the following example correspond to your use case ?

$ cat example.txt
:17.1
:17.12

With your map replacement, it gives 
$ cat example.txt | sandr -a map.txt
:17.12
:17.122

For me, it is normal : 
[:17.1] is replaced with [:17.12]
[:17.1]2 is replaced with [:17.12]2
because there is no replacement defined for :17.12

If you want that
:17.12 has the same value after replacement, you should add 
:17.12 => :17.12 
to your map.

**Comment by ajthemacboy** [comment]
Adding :17.12 fixed the replacement issues. I feel dumb for not realizing I needed to do that. Thank you for your help!

Another unrelated question; is there a way to add a character or something in the replacement map to delete any line that matches the pattern?

perhaps something like `:17.4 => {delete}`?

**Comment by jfgiraud** [comment]
sandr is a line per line tool.
You cannot delete a whole line that match a pattern. A line may contains one or more pattern to replace and the filename too (option -R).
You could replace a whole line with an empty line (ex : -S '^._7._$' -r '') but no more.
I prefer to use sed for this case. The aims of sandr is to replace (a string with another string)\* in each lines or filenames.
